[package]
name = "zed-pypackage-context"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
extensions = "0.2.0"
zed_extension_api = "0.1.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
