name = "PyPackage context"
version = "0.0.1"
schema_version = 1
authors = ["Philipp Temminghoff <philipptemminghoff@gmail.com>"]
description = "Slash commands for adding Python packages to the context"
repository = "https://github.com/phil65/zed-extension"
id = "pypackage-context"

[slash_commands.github]
description = "Provide a repo path (i.e. phil65/zed-extension)"
requires_argument = true

[slash_commands.pypi]
description = "Provide a PyPi package name"
requires_argument = true
